#!/usr/bin/env bash
set -e # Exit immediately if any command fails

echo "🚀 Starting NixOS configuration setup..."

# 1. Define paths
REPO_DIR="$HOME/dotfiles/nixos"
ETC_DIR="/etc/nixos"

# 2. Safety check: make sure we are running this from the cloned repo
if [ ! -f "$REPO_DIR/configuration.nix" ]; then
    echo "❌ Error: Could not find configuration.nix in $REPO_DIR"
    echo "Make sure this repo is cloned into ~/dotfiles/nixos"
    exit 1
fi

# 3. Clean up the default /etc/nixos folder generated by the installer
if [ -d "$ETC_DIR" ] && [ ! -L "$ETC_DIR" ]; then
    echo "📦 Backing up fresh installation files to /etc/nixos.bak..."
    sudo mv "$ETC_DIR" "${ETC_DIR}.bak"
elif [ -L "$ETC_DIR" ]; then
    echo "🔗 Found an existing symlink at $ETC_DIR, removing it to re-link..."
    sudo rm "$ETC_DIR"
fi

# 4. Create the system symlink
echo "🔗 Linking $REPO_DIR to $ETC_DIR..."
sudo ln -s "$REPO_DIR" "$ETC_DIR"

# 5. Build the system
echo "🔨 Running initial NixOS rebuild..."
sudo nixos-rebuild switch

echo "✅ Setup complete! Your system is now active and tracked by your dotfiles."
